### ISSUE TITLE
IRB integration error in OS Ventura

### ISSUE THREAD

**Issue by alexventuraio** [amazing-print/amazing_print#102]
I do not think it has to do with the OS at all but we'll see.
In order to get this working with Ruby 3.0.6 I did this:

1. Installing as Ruby gem:

    ```sh
    gem install amazing_print
    ```

2. I created a file at `~/.irbrc` with this content:
    ```
    require "amazing_print"
    AmazingPrint.irb!
    ```

Then when I enter the IRB console I got this error:
```ruby
± irb  
cannot load such file -- amazing_print  
4.0.6 :001 > 
```
Any thoughts on how to fix it?

**Comment by theomelo** [comment]
I am able to reproduce the issue on my Mac 
```ruby
irb(main):002:0> require 'amazing_print'
<internal:/Users/theo/.rbenv/versions/3.0.6/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- amazing_print (LoadError)
        from <internal:/Users/theo/.rbenv/versions/3.0.6/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from (irb):2:in `<main>'
        from /Users/theo/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/irb-1.3.5/exe/irb:11:in `<top (required)>'
        from /Users/theo/.rbenv/versions/3.0.6/bin/irb:23:in `load'
        from /Users/theo/.rbenv/versions/3.0.6/bin/irb:23:in `<
```
```
OS: Ventura 13.5.1
Ruby: 3.0.6
AmazingPrint: 1.5.0
```

The error doesn't happen for 3.2.2 (the version I'm using right now). @alexventuraio are you able to use a newer version of Ruby and check if you have the same issue?

**Comment by alexventuraio** [comment]
> 
> @alexventuraio are you able to use a newer version of Ruby and check if you have the same issue? Also, which version of `amazing_print` are you using?

Sorry for not providing such info, I'm using:
- Ruby `3.0.6`
- MacOS Ventura 13.2.1 (22D68)

<img width="464" alt="Screenshot 2023-09-01 at 9 04 04" src="https://github.com/amazing-print/amazing_print/assets/13169164/93c2de94-d799-4716-a527-3197b8d13513">

**Comment by HarlemSquirrel** [comment]
Can you require other gems you've installed while in IRB?

**Comment by alexventuraio** [comment]
> Can you require other gems you've installed while in IRB?

I think no if they are not in the project Gemfile:
```ruby
gem install awesome_print

± irb
cannot load such file -- amazing_print
3.0.6 :001 > require 'awesome_print'
(irb):1:in `require': cannot load such file -- awesome_print (LoadError)
	from (irb):1:in `<main>'
	from /Users/alex/.rvm/rubies/ruby-3.0.6/lib/ruby/gems/3.0.0/gems/irb-1.3.5/exe/irb:11:in `<top (required)>'
	from /Users/alex/.rvm/rubies/ruby-3.0.6/bin/irb:23:in `load'
	from /Users/alex/.rvm/rubies/ruby-3.0.6/bin/irb:23:in `<top (required)>'
	from /Users/alex/.rvm/rubies/ruby-3.0.6/lib/ruby/3.0.0/bundler/cli/exec.rb:58:in `load'
	from /Users/alex/.rvm/rubies/ruby-3.0.6/lib/ruby/3.0.0/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/alex/.rvm/rubies/ruby-3.0.6/lib/ruby/3.0.0/bundler/cli/exec.rb:23:in `run'
	from /Users/alex/.rvm/rubies/ruby-3.0.6/lib/ruby/3.0.0/bundler/cli.rb:479:in `exec'
	from /Users/alex/.rvm/rubies/ruby-3.0.6/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/alex/.rvm/rubies/ruby-3.0.6/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/alex/.rvm/rubies/ruby-3.0.6/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/alex/.rvm/rubies/ruby-3.0.6/lib/ruby/3.0.0/bundler/cli.rb:31:in `dispatch'
	from /Users/alex/.rvm/rubies/ruby-3.0.6/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/alex/.rvm/rubies/ruby-3.0.6/lib/ruby/3.0.0/bundler/cli.rb:25:in `start'
	from /Users/alex/.rvm/rubies/ruby-3.0.6/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/libexec/bundle:49:in `block in <top (required)>'
	from /Users/alex/.rvm/rubies/ruby-3.0.6/lib/ruby/3.0.0/bundler/friendly_errors.rb:103:in `with_friendly_errors'
	... 5 levels...
```

**Comment by HarlemSquirrel** [comment]
awesome_print is different.

Run `gem install amazing_print`

Then start `irb`

**Comment by alexventuraio** [comment]
> awesome_print is different.
> 
> Run `gem install amazing_print`
> 
> Then start `irb`

That's what I'm doing as per the image in my previous comment.

And I think it only happens if I run `irb` from within a Rails project folder and it seems to work when starting `irb` on a folder without a Rails app since I do not get the error message `cannot load such file -- amazing_print`.

**Comment by HarlemSquirrel** [comment]
Then it might be something to do with how GEM_HOME is set up for that project

**Comment by alexventuraio** [comment]
> Then it might be something to do with how GEM_HOME is set up for that project

Ok thanks for your support on this.
I'd love to see something covering/mentioning in the README file for when using it withing a Rails app.

**Comment by HarlemSquirrel** [comment]
@alexventuraio if you fully sort out what's going on then we may be able to put in our README so keep us posted here.

**Comment by HarlemSquirrel** [comment]
Let me know if we have something helpful to add to our README but going to close for now
