### ISSUE TITLE
ActiveModel::Errors can't modify frozen String

### ISSUE THREAD

**Issue by fire-pls** [amazing-print/amazing_print#40]
I encountered this error for `awesome_active_model_error` specifically, haven't seen it in any other formatters yet.
```ruby
[1] pry(main)> User.first.errors
(pry) output error: #<FrozenError: can't modify frozen String>
~/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/amazing_print-1.2.0/lib/amazing_print/ext/active_record.rb:100:in 
~/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/amazing_print-1.2.0/lib/amazing_print/formatter.rb:28:in `format'
~/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/amazing_print-1.2.0/lib/amazing_print/inspector.rb:124:in `unnested'
~/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/amazing_print-1.2.0/lib/amazing_print/inspector.rb:79:in `awesome'
~/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/amazing_print-1.2.0/lib/amazing_print/core_ext/kernel.rb:11:in `ai'
# rest is pry stack
```

Here's my aprc:
```
AmazingPrint.defaults = {
  indent: -2,
  index: false,
  color: { args: :whiteish, array: :white, bigdecimal: :blue, class: :purpleish, date: :whiteish, falseclass: :cyanish, integer: :blue, float: :blue, hash: :whiteish, keyword: :cyan, method: :purple, nilclass: :gray, rational: :blue, string: :redish, struct: :purpleish, symbol: :purpleish, time: :whiteish, trueclass: :cyan, variable: :cyanish },
}
```

I've got a working branch I can open a PR with later today.

## Affected (tested) versions
Ruby
- `2.7.1`
- `2.6.6`
- `2.5.8`
Rails
- `6.0.3`

**Comment by ritec** [comment]
I am having a similar issue to this with some of my models. Using the latest version `1.3.0` and `Ruby 2.7.3`
```
irb(main):013:0> ap User.first
Traceback (most recent call last):
FrozenError (can't modify frozen String: "true")
irb(main):014:0> ap User.last
Traceback (most recent call last):
FrozenError (can't modify frozen String: "false")
```
