### ISSUE TITLE
"can't modify frozen String" error when using Ruby1.9 syntax and left-align

### ISSUE THREAD

**Issue by stefanwascoding** [amazing-print/amazing_print#52]
Using the following code (no existing `.aprc` file):

```
puts AmazingPrint.version
h = {a: "b", cde: "f"}
puts "plain"
ap(h)
puts "ruby19_syntax"
ap(h, ruby19_syntax: true)
puts "left align"
ap(h, indent: -2)
puts "left aligned ruby19_syntax"
ap(h, ruby19_syntax: true, indent: -2)
```

you get the following (expected) output using v1.1.0 of AmazingPrint:

```
1.1.0
plain
{
      :a => "b",
    :cde => "f"
}
ruby19_syntax
{
      a: "b",
    cde: "f"
}
left align
{
  :a   => "b",
  :cde => "f"
}
left aligned ruby19_syntax
{
  a  : "b",
  cde: "f"
}
```

Starting from version 1.2.0 including to latest git (as of writing), you get a `FrozenError` on that last test:

```
1.2.2.pre
plain
{
      :a => "b",
    :cde => "f"
}
ruby19_syntax
{
      a: "b",
    cde: "f"
}
left align
{
  :a   => "b",
  :cde => "f"
}
left aligned ruby19_syntax
Traceback (most recent call last):
	16: from test-ap.rb:14:in `<main>'
	15: from ~ap_checkout/core_ext/kernel.rb:21:in `ap'
	14: from ~ap_checkout/core_ext/kernel.rb:11:in `ai'
	13: from ~ap_checkout/inspector.rb:79:in `awesome'
	12: from ~ap_checkout/inspector.rb:124:in `unnested'
	11: from ~ap_checkout/formatter.rb:28:in `format'
	10: from ~ap_checkout/formatter.rb:81:in `awesome_hash'
	 9: from ~ap_checkout/formatters/hash_formatter.rb:20:in `format'
	 8: from ~ap_checkout/formatters/hash_formatter.rb:37:in `multiline_hash'
	 7: from ~ap_checkout/formatters/hash_formatter.rb:48:in `printable_hash'
	 6: from ~ap_checkout/formatters/hash_formatter.rb:48:in `map!'
	 5: from ~ap_checkout/formatters/hash_formatter.rb:49:in `block in printable_hash'
	 4: from ~ap_checkout/formatters/base_formatter.rb:119:in `indented'
	 3: from ~ap_checkout/inspector.rb:68:in `increase_indentation'
	 2: from ~ap_checkout/indentator.rb:14:in `indent'
	 1: from ~ap_checkout/formatters/hash_formatter.rb:51:in `block (2 levels) in printable_hash'
~ap_checkout/formatters/hash_formatter.rb:89:in `ruby19_syntax': can't modify frozen String: "  a  " (FrozenError)
```

**Comment by stefanwascoding** [comment]
Works after https://github.com/amazing-print/amazing_print/pull/51
