### ISSUE TITLE
Problems in use Rack::Test

### ISSUE THREAD

**Issue by AlexeyMatskevich** [amazing-print/amazing_print#62]
i switched from awesome_print to this game. When I try debug with pry I have problem with Rack::Test #last_response

```ruby
[1] pry(#<RSpec::ExampleGroups::Logout::GET::WhenUserLoggedIn>)> last_response
(pry) output error: #<NoMethodError: undefined method `gmtime' for "Thu, 01 Jan 1970 00:00:00 GMT":String>
/usr/local/lib/ruby/2.7.0/cgi/util.rb:188:in `rfc1123_date'
/usr/local/lib/ruby/2.7.0/cgi/cookie.rb:143:in `to_s'
/usr/local/lib/ruby/2.7.0/cgi/cookie.rb:176:in `inspect'
/usr/local/bundle/gems/amazing_print-1.2.2/lib/amazing_print/formatter.rb:52:in `inspect'
/usr/local/bundle/gems/amazing_print-1.2.2/lib/amazing_print/formatter.rb:52:in `inspect'
/usr/local/bundle/gems/amazing_print-1.2.2/lib/amazing_print/formatter.rb:52:in `awesome_self'
/usr/local/bundle/gems/amazing_print-1.2.2/lib/amazing_print/formatter.rb:30:in `format'
/usr/local/bundle/gems/amazing_print-1.2.2/lib/amazing_print/inspector.rb:124:in `unnested'
/usr/local/bundle/gems/amazing_print-1.2.2/lib/amazing_print/inspector.rb:79:in `awesome'
/usr/local/bundle/gems/amazing_print-1.2.2/lib/amazing_print/core_ext/kernel.rb:11:in `ai'
/usr/local/bundle/gems/amazing_print-1.2.2/lib/amazing_print/custom_defaults.rb:47:in `block in pry!'
/usr/local/bundle/gems/pry-0.13.1/lib/pry/pry_instance.rb:302:in `show_result'
/usr/local/bundle/gems/pry-0.13.1/lib/pry/pry_instance.rb:672:in `block in handle_line'
/usr/local/bundle/gems/pry-0.13.1/lib/pry/pry_class.rb:382:in `critical_section'
/usr/local/bundle/gems/pry-0.13.1/lib/pry/pry_instance.rb:671:in `handle_line'
/usr/local/bundle/gems/pry-0.13.1/lib/pry/pry_instance.rb:261:in `block (2 levels) in eval'
/usr/local/bundle/gems/pry-0.13.1/lib/pry/pry_instance.rb:260:in `catch'
/usr/local/bundle/gems/pry-0.13.1/lib/pry/pry_instance.rb:260:in `block in eval'
/usr/local/bundle/gems/pry-0.13.1/lib/pry/pry_instance.rb:259:in `catch'
/usr/local/bundle/gems/pry-0.13.1/lib/pry/pry_instance.rb:259:in `eval'
/usr/local/bundle/gems/pry-0.13.1/lib/pry/repl.rb:77:in `block in repl'
/usr/local/bundle/gems/pry-0.13.1/lib/pry/repl.rb:67:in `loop'
/usr/local/bundle/gems/pry-0.13.1/lib/pry/repl.rb:67:in `repl'
/usr/local/bundle/gems/pry-0.13.1/lib/pry/repl.rb:38:in `block in start'
/usr/local/bundle/gems/pry-0.13.1/lib/pry/input_lock.rb:61:in `__with_ownership'
/usr/local/bundle/gems/pry-0.13.1/lib/pry/input_lock.rb:78:in `with_ownership'
/usr/local/bundle/gems/pry-0.13.1/lib/pry/repl.rb:38:in `start'
/usr/local/bundle/gems/pry-0.13.1/lib/pry/repl.rb:15:in `start'
/usr/local/bundle/gems/pry-0.13.1/lib/pry/pry_class.rb:191:in `start'
/usr/local/bundle/gems/pry-0.13.1/lib/pry/core_extensions.rb:45:in `pry'
/app/spec/request/logout_spec.rb:32:in `block (4 levels) in <top (required)>'
/usr/local/bundle/gems/rspec-core-3.9.3/lib/rspec/core/example.rb:262:in `instance_exec'
/usr/local/bundle/gems/rspec-core-3.9.3/lib/rspec/core/example.rb:262:in `block in run'
/usr/local/bundle/gems/rspec-core-3.9.3/lib/rspec/core/example.rb:508:in `block in with_around_and_singleton_context_hooks'
/usr/local/bundle/gems/rspec-core-3.9.3/lib/rspec/core/example.rb:465:in `block in with_around_example_hooks'
/usr/local/bundle/gems/rspec-core-3.9.3/lib/rspec/core/hooks.rb:486:in `block in run'
/usr/local/bundle/gems/rspec-core-3.9.3/lib/rspec/core/hooks.rb:624:in `run_around_example_hooks_for'
/usr/local/bundle/gems/rspec-core-3.9.3/lib/rspec/core/hooks.rb:486:in `run'
/usr/local/bundle/gems/rspec-core-3.9.3/lib/rspec/core/example.rb:465:in `with_around_example_hooks'
/usr/local/bundle/gems/rspec-core-3.9.3/lib/rspec/core/example.rb:508:in `with_around_and_singleton_context_hooks'
/usr/local/bundle/gems/rspec-core-3.9.3/lib/rspec/core/example.rb:259:in `run'
/usr/local/bundle/gems/rspec-core-3.9.3/lib/rspec/core/example_group.rb:644:in `block in run_examples'
/usr/local/bundle/gems/rspec-core-3.9.3/lib/rspec/core/example_group.rb:640:in `map'
/usr/local/bundle/gems/rspec-core-3.9.3/lib/rspec/core/example_group.rb:640:in `run_examples'
/usr/local/bundle/gems/rspec-core-3.9.3/lib/rspec/core/example_group.rb:606:in `run'
/usr/local/bundle/gems/rspec-core-3.9.3/lib/rspec/core/example_group.rb:607:in `block in run'
/usr/local/bundle/gems/rspec-core-3.9.3/lib/rspec/core/example_group.rb:607:in `map'
/usr/local/bundle/gems/rspec-core-3.9.3/lib/rspec/core/example_group.rb:607:in `run'
/usr/local/bundle/gems/rspec-core-3.9.3/lib/rspec/core/example_group.rb:607:in `block in run'
/usr/local/bundle/gems/rspec-core-3.9.3/lib/rspec/core/example_group.rb:607:in `map'
/usr/local/bundle/gems/rspec-core-3.9.3/lib/rspec/core/example_group.rb:607:in `run'
/usr/local/bundle/gems/rspec-core-3.9.3/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'
/usr/local/bundle/gems/rspec-core-3.9.3/lib/rspec/core/runner.rb:121:in `map'
/usr/local/bundle/gems/rspec-core-3.9.3/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'
/usr/local/bundle/gems/rspec-core-3.9.3/lib/rspec/core/configuration.rb:2061:in `with_suite_hooks'
/usr/local/bundle/gems/rspec-core-3.9.3/lib/rspec/core/runner.rb:116:in `block in run_specs'
/usr/local/bundle/gems/rspec-core-3.9.3/lib/rspec/core/reporter.rb:74:in `report'
/usr/local/bundle/gems/rspec-core-3.9.3/lib/rspec/core/runner.rb:115:in `run_specs'
/usr/local/bundle/gems/rspec-core-3.9.3/lib/rspec/core/runner.rb:89:in `run'
/usr/local/bundle/gems/rspec-core-3.9.3/lib/rspec/core/runner.rb:71:in `run'
/usr/local/bundle/gems/rspec-core-3.9.3/lib/rspec/core/runner.rb:45:in `invoke'
/usr/local/bundle/gems/rspec-core-3.9.3/exe/rspec:4:in `<top (required)>'
/usr/local/bundle/bin/rspec:23:in `load'
/usr/local/bundle/bin/rspec:23:in `<main>'
```
Any idea why this is happening?

**Comment by speckins** [comment]
This is most likely a Rack issue.  I don't use amazing_print, but I came across this issue via Google when trying to debug the same error, and eventually opened an issue with the rack gem.  It's since been fixed.

https://github.com/rack/rack/issues/1758

**Comment by AlexeyMatskevich** [comment]
I think we can close this issue.
